esphome:
  name: atom-lite-btproxy
  friendly_name: Atom Lite Bluetooth Proxy

esp32:
  board: m5stack-atom
  framework:
    type: arduino

logger:

api:

ota:

wifi:
  ssid: "mycastle01_02"
  password: "1Wsb5&30=?21Home"
  ap:
    ssid: "atom-lite-fallback"
    password: "fallback1234"

captive_portal:

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
