name: Build ESPHome firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build ESPHome firmware
        uses: esphome/build-action@v3
        with:
          yaml_file: atom-lite-btproxy.yaml
