name: Build ESPHome Firmware

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build firmware
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build with ESPHome
        uses: esphome/build-action@v3
        with:
          yaml_file: atom-lite-btproxy.yaml
